planner_configs:
  RRTConnect:
    type: geometric::RRTConnect
    range: 0.5
    goal_bias: 0.05
  RRTstar:
    type: geometric::RRTstar
    range: 0.5
    goal_bias: 0.05
    delay_collision_checking: 1
  PRMstar:
    type: geometric::PRMstar
  FMT:
    type: geometric::FMT
  BFMT:
    type: geometric::BFMT
  LBKPIECE:
    type: geometric::LBKPIECE
    range: 0.0  # Max step size to take in space
  BKPIECE:
    type: geometric::BKPIECE
    range: 0.0  # Max step size to take in space




arm_robot:  # replace 'arm' with your actual planning group name
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRTstar
    - PRMstar
    - FMT
    - BFMT
    - LBKPIECE
    - BKPIECE
  projection_evaluator: joints(arm_base_forearm_joint,forearm_hand_1_joint)  # replace with your actual joint names
  longest_valid_segment_fraction: 0.005


gripper:
  default_planner_config: RRTConnect
  planner_configs:
    - RRTConnect
    - RRTstar
  projection_evaluator: joints(finger_joint1,finger_joint2)
  longest_valid_segment_fraction: 0.005
  
# plan_execution:
#   execution_duration_monitoring: true
#   allowed_execution_duration_scaling: 1.2
#   allowed_goal_duration_margin: 0.5
#   allowed_start_tolerance: 0.01

# planning_scene_monitor:
#   publish_planning_scene: true
#   publish_geometry_updates: true
#   publish_state_updates: true
#   publish_transforms_updates: true

# # Additional OMPL parameters
# ompl:
#   planning_time_limit: 10.0
#   max_goal_samples: 10000
#   max_planning_threads: 4
#   simplify_solutions: true


# planning_plugin: 'ompl_interface/OMPLPlanner'
# request_adapters:
#     default_planner_request_adapters/AddTimeOptimalParameterization
#     default_planner_request_adapters/FixWorkspaceBounds
#     default_planner_request_adapters/FixStartStateBounds
#     default_planner_request_adapters/FixStartStateCollision
#     default_planner_request_adapters/FixStartStatePathConstraints
# start_state_max_bounds_error: 0.1